CREATE TABLE countries(
   id   serial  NOT NULL PRIMARY KEY 
  ,code CHAR(2) 
  ,name VARCHAR(50) 
);
INSERT INTO countries(id,code,name) VALUES (1,'AF','Afghanistan');
INSERT INTO countries(id,code,name) VALUES (2,'AX','Aland Islands');
INSERT INTO countries(id,code,name) VALUES (3,'AL','Albania');
INSERT INTO countries(id,code,name) VALUES (4,'DZ','Algeria');
INSERT INTO countries(id,code,name) VALUES (5,'AS','American Samoa');
INSERT INTO countries(id,code,name) VALUES (6,'AD','Andorra');
INSERT INTO countries(id,code,name) VALUES (7,'AO','Angola');
INSERT INTO countries(id,code,name) VALUES (8,'AI','Anguilla');
INSERT INTO countries(id,code,name) VALUES (9,'AQ','Antarctica');
INSERT INTO countries(id,code,name) VALUES (10,'AG','Antigua and Barbuda');
INSERT INTO countries(id,code,name) VALUES (11,'AR','Argentina');
INSERT INTO countries(id,code,name) VALUES (12,'AM','Armenia');
INSERT INTO countries(id,code,name) VALUES (13,'AW','Aruba');
INSERT INTO countries(id,code,name) VALUES (14,'AU','Australia');
INSERT INTO countries(id,code,name) VALUES (15,'AT','Austria');
INSERT INTO countries(id,code,name) VALUES (16,'AZ','Azerbaijan');
INSERT INTO countries(id,code,name) VALUES (17,'ST','Sao Tome and Principe');
INSERT INTO countries(id,code,name) VALUES (18,'BS','Bahamas');
INSERT INTO countries(id,code,name) VALUES (19,'BH','Bahrain');
INSERT INTO countries(id,code,name) VALUES (20,'BD','Bangladesh');
INSERT INTO countries(id,code,name) VALUES (21,'BB','Barbados');
INSERT INTO countries(id,code,name) VALUES (22,'BY','Belarus');
INSERT INTO countries(id,code,name) VALUES (23,'BE','Belgium');
INSERT INTO countries(id,code,name) VALUES (24,'BZ','Belize');
INSERT INTO countries(id,code,name) VALUES (25,'BJ','Benin');
INSERT INTO countries(id,code,name) VALUES (26,'BT','Bhutan');
INSERT INTO countries(id,code,name) VALUES (27,'BO','Bolivia');
INSERT INTO countries(id,code,name) VALUES (28,'BA','Bosnia and Herzegovina');
INSERT INTO countries(id,code,name) VALUES (29,'BW','Botswana');
INSERT INTO countries(id,code,name) VALUES (30,'BV','Bouvet Island');
INSERT INTO countries(id,code,name) VALUES (31,'BR','Brazil');
INSERT INTO countries(id,code,name) VALUES (32,'VG','British Virgin Islands');
INSERT INTO countries(id,code,name) VALUES (33,'IO','British Indian Ocean Territory');
INSERT INTO countries(id,code,name) VALUES (34,'BN','Brunei Darussalam');
INSERT INTO countries(id,code,name) VALUES (35,'BG','Bulgaria');
INSERT INTO countries(id,code,name) VALUES (36,'BF','Burkina Faso');
INSERT INTO countries(id,code,name) VALUES (37,'BI','Burundi');
INSERT INTO countries(id,code,name) VALUES (38,'KH','Cambodia');
INSERT INTO countries(id,code,name) VALUES (39,'CM','Cameroon');
INSERT INTO countries(id,code,name) VALUES (40,'CA','Canada');
INSERT INTO countries(id,code,name) VALUES (41,'CV','Cape Verde');
INSERT INTO countries(id,code,name) VALUES (42,'KY','Cayman Islands');
INSERT INTO countries(id,code,name) VALUES (43,'CF','Central African Republic');
INSERT INTO countries(id,code,name) VALUES (44,'TD','Chad');
INSERT INTO countries(id,code,name) VALUES (45,'CL','Chile');
INSERT INTO countries(id,code,name) VALUES (46,'CN','China');
INSERT INTO countries(id,code,name) VALUES (47,'HK','Hong Kong, SAR China');
INSERT INTO countries(id,code,name) VALUES (48,'CR','Costa Rica');
INSERT INTO countries(id,code,name) VALUES (49,'MO','Macao, SAR China');
INSERT INTO countries(id,code,name) VALUES (50,'CX','Christmas Island');
INSERT INTO countries(id,code,name) VALUES (51,'CC','Cocos (Keeling) Islands');
INSERT INTO countries(id,code,name) VALUES (52,'CO','Colombia');
INSERT INTO countries(id,code,name) VALUES (53,'KM','Comoros');
INSERT INTO countries(id,code,name) VALUES (54,'CD','Congo, (Kinshasa)');
INSERT INTO countries(id,code,name) VALUES (55,'CK','Cook Islands');
INSERT INTO countries(id,code,name) VALUES (56,'CI','Côte d''Ivoire');
INSERT INTO countries(id,code,name) VALUES (57,'HR','Croatia');
INSERT INTO countries(id,code,name) VALUES (58,'CU','Cuba');
INSERT INTO countries(id,code,name) VALUES (59,'CY','Cyprus');
INSERT INTO countries(id,code,name) VALUES (60,'CZ','Czech Republic');
INSERT INTO countries(id,code,name) VALUES (61,'DK','Denmark');
INSERT INTO countries(id,code,name) VALUES (62,'DJ','Djibouti');
INSERT INTO countries(id,code,name) VALUES (63,'DM','Dominica');
INSERT INTO countries(id,code,name) VALUES (64,'DO','Dominican Republic');
INSERT INTO countries(id,code,name) VALUES (65,'EC','Ecuador');
INSERT INTO countries(id,code,name) VALUES (66,'EG','Egypt');
INSERT INTO countries(id,code,name) VALUES (67,'SV','El Salvador');
INSERT INTO countries(id,code,name) VALUES (68,'GQ','Equatorial Guinea');
INSERT INTO countries(id,code,name) VALUES (69,'ER','Eritrea');
INSERT INTO countries(id,code,name) VALUES (70,'EE','Estonia');
INSERT INTO countries(id,code,name) VALUES (71,'ET','Ethiopia');
INSERT INTO countries(id,code,name) VALUES (72,'FK','Falkland Islands (Malvinas)');
INSERT INTO countries(id,code,name) VALUES (73,'FO','Faroe Islands');
INSERT INTO countries(id,code,name) VALUES (74,'FJ','Fiji');
INSERT INTO countries(id,code,name) VALUES (75,'FI','Finland');
INSERT INTO countries(id,code,name) VALUES (76,'FR','France');
INSERT INTO countries(id,code,name) VALUES (77,'GF','French Guiana');
INSERT INTO countries(id,code,name) VALUES (78,'PF','French Polynesia');
INSERT INTO countries(id,code,name) VALUES (79,'TF','French Southern Territories');
INSERT INTO countries(id,code,name) VALUES (80,'GA','Gabon');
INSERT INTO countries(id,code,name) VALUES (81,'GM','Gambia');
INSERT INTO countries(id,code,name) VALUES (82,'GE','Georgia');
INSERT INTO countries(id,code,name) VALUES (83,'DE','Germany');
INSERT INTO countries(id,code,name) VALUES (84,'GH','Ghana');
INSERT INTO countries(id,code,name) VALUES (85,'GI','Gibraltar');
INSERT INTO countries(id,code,name) VALUES (86,'GR','Greece');
INSERT INTO countries(id,code,name) VALUES (87,'GL','Greenland');
INSERT INTO countries(id,code,name) VALUES (88,'GD','Grenada');
INSERT INTO countries(id,code,name) VALUES (89,'GP','Guadeloupe');
INSERT INTO countries(id,code,name) VALUES (90,'GU','Guam');
INSERT INTO countries(id,code,name) VALUES (91,'GT','Guatemala');
INSERT INTO countries(id,code,name) VALUES (92,'GG','Guernsey');
INSERT INTO countries(id,code,name) VALUES (93,'GN','Guinea');
INSERT INTO countries(id,code,name) VALUES (94,'GW','Guinea-Bissau');
INSERT INTO countries(id,code,name) VALUES (95,'GY','Guyana');
INSERT INTO countries(id,code,name) VALUES (96,'HT','Haiti');
INSERT INTO countries(id,code,name) VALUES (97,'HM','Heard and Mcdonald Islands');
INSERT INTO countries(id,code,name) VALUES (98,'VA','Holy See (Vatican City State)');
INSERT INTO countries(id,code,name) VALUES (99,'HN','Honduras');
INSERT INTO countries(id,code,name) VALUES (100,'HU','Hungary');
INSERT INTO countries(id,code,name) VALUES (101,'IS','Iceland');
INSERT INTO countries(id,code,name) VALUES (102,'FM','Micronesia, Federated States of');
INSERT INTO countries(id,code,name) VALUES (103,'RE','Réunion');
INSERT INTO countries(id,code,name) VALUES (104,'ID','Indonesia');
INSERT INTO countries(id,code,name) VALUES (105,'IR','Iran, Islamic Republic of');
INSERT INTO countries(id,code,name) VALUES (106,'IQ','Iraq');
INSERT INTO countries(id,code,name) VALUES (107,'IE','Ireland');
INSERT INTO countries(id,code,name) VALUES (108,'IM','Isle of Man');
INSERT INTO countries(id,code,name) VALUES (109,'IL','Israel');
INSERT INTO countries(id,code,name) VALUES (110,'IT','Italy');
INSERT INTO countries(id,code,name) VALUES (111,'JM','Jamaica');
INSERT INTO countries(id,code,name) VALUES (112,'JP','Japan');
INSERT INTO countries(id,code,name) VALUES (113,'JE','Jersey');
INSERT INTO countries(id,code,name) VALUES (114,'JO','Jordan');
INSERT INTO countries(id,code,name) VALUES (115,'MD','Moldova');
INSERT INTO countries(id,code,name) VALUES (116,'KZ','Kazakhstan');
INSERT INTO countries(id,code,name) VALUES (117,'KE','Kenya');
INSERT INTO countries(id,code,name) VALUES (118,'KI','Kiribati');
INSERT INTO countries(id,code,name) VALUES (119,'KP','Korea (North)');
INSERT INTO countries(id,code,name) VALUES (120,'KR','Korea (South)');
INSERT INTO countries(id,code,name) VALUES (121,'KW','Kuwait');
INSERT INTO countries(id,code,name) VALUES (122,'KG','Kyrgyzstan');
INSERT INTO countries(id,code,name) VALUES (123,'LA','Lao PDR');
INSERT INTO countries(id,code,name) VALUES (124,'LV','Latvia');
INSERT INTO countries(id,code,name) VALUES (125,'LB','Lebanon');
INSERT INTO countries(id,code,name) VALUES (126,'LS','Lesotho');
INSERT INTO countries(id,code,name) VALUES (127,'LR','Liberia');
INSERT INTO countries(id,code,name) VALUES (128,'LY','Libya');
INSERT INTO countries(id,code,name) VALUES (129,'LI','Liechtenstein');
INSERT INTO countries(id,code,name) VALUES (130,'LT','Lithuania');
INSERT INTO countries(id,code,name) VALUES (131,'LU','Luxembourg');
INSERT INTO countries(id,code,name) VALUES (132,'MK','Macedonia, Republic of');
INSERT INTO countries(id,code,name) VALUES (133,'MG','Madagascar');
INSERT INTO countries(id,code,name) VALUES (134,'MW','Malawi');
INSERT INTO countries(id,code,name) VALUES (135,'MY','Malaysia');
INSERT INTO countries(id,code,name) VALUES (136,'MV','Maldives');
INSERT INTO countries(id,code,name) VALUES (137,'BM','Bermuda');
INSERT INTO countries(id,code,name) VALUES (138,'ML','Mali');
INSERT INTO countries(id,code,name) VALUES (139,'MT','Malta');
INSERT INTO countries(id,code,name) VALUES (140,'MH','Marshall Islands');
INSERT INTO countries(id,code,name) VALUES (141,'MQ','Martinique');
INSERT INTO countries(id,code,name) VALUES (142,'MR','Mauritania');
INSERT INTO countries(id,code,name) VALUES (143,'MU','Mauritius');
INSERT INTO countries(id,code,name) VALUES (144,'YT','Mayotte');
INSERT INTO countries(id,code,name) VALUES (145,'MX','Mexico');
INSERT INTO countries(id,code,name) VALUES (146,'MC','Monaco');
INSERT INTO countries(id,code,name) VALUES (147,'MN','Mongolia');
INSERT INTO countries(id,code,name) VALUES (148,'ME','Montenegro');
INSERT INTO countries(id,code,name) VALUES (149,'MS','Montserrat');
INSERT INTO countries(id,code,name) VALUES (150,'MA','Morocco');
INSERT INTO countries(id,code,name) VALUES (151,'MZ','Mozambique');
INSERT INTO countries(id,code,name) VALUES (152,'MM','Myanmar');
INSERT INTO countries(id,code,name) VALUES (153,'NA','Namibia');
INSERT INTO countries(id,code,name) VALUES (154,'NR','Nauru');
INSERT INTO countries(id,code,name) VALUES (155,'NP','Nepal');
INSERT INTO countries(id,code,name) VALUES (156,'NL','Netherlands');
INSERT INTO countries(id,code,name) VALUES (157,'AN','Netherlands Antilles');
INSERT INTO countries(id,code,name) VALUES (158,'NC','New Caledonia');
INSERT INTO countries(id,code,name) VALUES (159,'NZ','New Zealand');
INSERT INTO countries(id,code,name) VALUES (160,'NI','Nicaragua');
INSERT INTO countries(id,code,name) VALUES (161,'NE','Niger');
INSERT INTO countries(id,code,name) VALUES (162,'NG','Nigeria');
INSERT INTO countries(id,code,name) VALUES (163,'NU','Niue');
INSERT INTO countries(id,code,name) VALUES (164,'NF','Norfolk Island');
INSERT INTO countries(id,code,name) VALUES (165,'MP','Northern Mariana Islands');
INSERT INTO countries(id,code,name) VALUES (166,'NO','Norway');
INSERT INTO countries(id,code,name) VALUES (167,'OM','Oman');
INSERT INTO countries(id,code,name) VALUES (168,'PK','Pakistan');
INSERT INTO countries(id,code,name) VALUES (169,'PW','Palau');
INSERT INTO countries(id,code,name) VALUES (170,'PS','Palestinian Territory');
INSERT INTO countries(id,code,name) VALUES (171,'PA','Panama');
INSERT INTO countries(id,code,name) VALUES (172,'PG','Papua New Guinea');
INSERT INTO countries(id,code,name) VALUES (173,'PY','Paraguay');
INSERT INTO countries(id,code,name) VALUES (174,'PE','Peru');
INSERT INTO countries(id,code,name) VALUES (175,'PH','Philippines');
INSERT INTO countries(id,code,name) VALUES (176,'PN','Pitcairn');
INSERT INTO countries(id,code,name) VALUES (177,'PT','Portugal');
INSERT INTO countries(id,code,name) VALUES (178,'PR','Puerto Rico');
INSERT INTO countries(id,code,name) VALUES (179,'QA','Qatar');
INSERT INTO countries(id,code,name) VALUES (180,'RO','Romania');
INSERT INTO countries(id,code,name) VALUES (181,'RU','Russian Federation');
INSERT INTO countries(id,code,name) VALUES (182,'RW','Rwanda');
INSERT INTO countries(id,code,name) VALUES (183,'BL','Saint-Barthélemy');
INSERT INTO countries(id,code,name) VALUES (184,'SH','Saint Helena');
INSERT INTO countries(id,code,name) VALUES (185,'KN','Saint Kitts and Nevis');
INSERT INTO countries(id,code,name) VALUES (186,'LC','Saint Lucia');
INSERT INTO countries(id,code,name) VALUES (187,'MF','Saint-Martin (French part)');
INSERT INTO countries(id,code,name) VALUES (188,'PM','Saint Pierre and Miquelon');
INSERT INTO countries(id,code,name) VALUES (189,'VC','Saint Vincent and Grenadines');
INSERT INTO countries(id,code,name) VALUES (190,'WS','Samoa');
INSERT INTO countries(id,code,name) VALUES (191,'SM','San Marino');
INSERT INTO countries(id,code,name) VALUES (192,'SA','Saudi Arabia');
INSERT INTO countries(id,code,name) VALUES (193,'SN','Senegal');
INSERT INTO countries(id,code,name) VALUES (194,'RS','Serbia');
INSERT INTO countries(id,code,name) VALUES (195,'SC','Seychelles');
INSERT INTO countries(id,code,name) VALUES (196,'SL','Sierra Leone');
INSERT INTO countries(id,code,name) VALUES (197,'SG','Singapore');
INSERT INTO countries(id,code,name) VALUES (198,'SK','Slovakia');
INSERT INTO countries(id,code,name) VALUES (199,'SI','Slovenia');
INSERT INTO countries(id,code,name) VALUES (200,'SB','Solomon Islands');
INSERT INTO countries(id,code,name) VALUES (201,'SO','Somalia');
INSERT INTO countries(id,code,name) VALUES (202,'ZA','South Africa');
INSERT INTO countries(id,code,name) VALUES (203,'GS','South Georgia and the South Sandwich Islands');
INSERT INTO countries(id,code,name) VALUES (204,'SS','South Sudan');
INSERT INTO countries(id,code,name) VALUES (205,'ES','Spain');
INSERT INTO countries(id,code,name) VALUES (206,'LK','Sri Lanka');
INSERT INTO countries(id,code,name) VALUES (207,'SD','Sudan');
INSERT INTO countries(id,code,name) VALUES (208,'SR','Suriname');
INSERT INTO countries(id,code,name) VALUES (209,'SJ','Svalbard and Jan Mayen Islands');
INSERT INTO countries(id,code,name) VALUES (210,'SZ','Swaziland');
INSERT INTO countries(id,code,name) VALUES (211,'SE','Sweden');
INSERT INTO countries(id,code,name) VALUES (212,'CH','Switzerland');
INSERT INTO countries(id,code,name) VALUES (213,'SY','Syrian Arab Republic (Syria)');
INSERT INTO countries(id,code,name) VALUES (214,'TW','Taiwan, Republic of China');
INSERT INTO countries(id,code,name) VALUES (215,'TJ','Tajikistan');
INSERT INTO countries(id,code,name) VALUES (216,'TZ','Tanzania, United Republic of');
INSERT INTO countries(id,code,name) VALUES (217,'TH','Thailand');
INSERT INTO countries(id,code,name) VALUES (218,'IN','India');
INSERT INTO countries(id,code,name) VALUES (219,'CG','Congo (Brazzaville)');
INSERT INTO countries(id,code,name) VALUES (220,'PL','Poland');
INSERT INTO countries(id,code,name) VALUES (221,'TL','Timor-Leste');
INSERT INTO countries(id,code,name) VALUES (222,'TG','Togo');
INSERT INTO countries(id,code,name) VALUES (223,'TK','Tokelau');
INSERT INTO countries(id,code,name) VALUES (224,'TO','Tonga');
INSERT INTO countries(id,code,name) VALUES (225,'TT','Trinidad and Tobago');
INSERT INTO countries(id,code,name) VALUES (226,'TN','Tunisia');
INSERT INTO countries(id,code,name) VALUES (227,'TR','Turkey');
INSERT INTO countries(id,code,name) VALUES (228,'TM','Turkmenistan');
INSERT INTO countries(id,code,name) VALUES (229,'TC','Turks and Caicos Islands');
INSERT INTO countries(id,code,name) VALUES (230,'TV','Tuvalu');
INSERT INTO countries(id,code,name) VALUES (231,'UG','Uganda');
INSERT INTO countries(id,code,name) VALUES (232,'UA','Ukraine');
INSERT INTO countries(id,code,name) VALUES (233,'AE','United Arab Emirates');
INSERT INTO countries(id,code,name) VALUES (234,'GB','United Kingdom');
INSERT INTO countries(id,code,name) VALUES (235,'US','United States of America');
INSERT INTO countries(id,code,name) VALUES (236,'UM','US Minor Outlying Islands');
INSERT INTO countries(id,code,name) VALUES (237,'UY','Uruguay');
INSERT INTO countries(id,code,name) VALUES (238,'UZ','Uzbekistan');
INSERT INTO countries(id,code,name) VALUES (239,'VU','Vanuatu');
INSERT INTO countries(id,code,name) VALUES (240,'VE','Venezuela (Bolivarian Republic)');
INSERT INTO countries(id,code,name) VALUES (241,'VN','Viet Nam');
INSERT INTO countries(id,code,name) VALUES (242,'VI','Virgin Islands, US');
INSERT INTO countries(id,code,name) VALUES (243,'WF','Wallis and Futuna Islands');
INSERT INTO countries(id,code,name) VALUES (244,'EH','Western Sahara');
INSERT INTO countries(id,code,name) VALUES (245,'YE','Yemen');
INSERT INTO countries(id,code,name) VALUES (246,'ZM','Zambia');
INSERT INTO countries(id,code,name) VALUES (247,'ZW','Zimbabwe');



CREATE TABLE users(
id SERIAL PRIMARY KEY,
name VARCHAR(15) UNIQUE NOT NULL,
color VARCHAR(15)
);

CREATE TABLE visited_countries(
id SERIAL PRIMARY KEY,
country_code CHAR(2) NOT NULL,
user_id INTEGER REFERENCES users(id)
);

INSERT INTO users (name, color)
VALUES ('Angela', 'teal'), ('Jack', 'powderblue');

INSERT INTO visited_countries (country_code, user_id)
VALUES ('FR', 1), ('GB', 1), ('CA', 2), ('FR', 2 );

SELECT *
FROM visited_countries
JOIN users
ON users.id = user_id;